config/routes.rb
Corobook::Application.routes.draw do

  resources :anniversaries


  resources :settings


  mount Ckeditor::Engine => '/ckeditor'

  resources :group_collaborators
  resources :groups
  resources :diapos
  resources :presentations do 
    member do 
      get :live
    end
  end

  resources :user_groups


  resources :songbooks do 
    member do 
      get :send_email
    end
  end


  resources :songs do
    member do 
      get :live
    end

    collection do
      get :vote_add
      get :songbook_add
      get :songbook_remove
    end
  end


  # authenticated :user do
  #   root :to => 'songs#index'
  # end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  attr_accessible :fecha, :contents_attributes
  has_many :contents, :order => 'position ASC', :dependent => :destroy
  belongs_to :church
  
  paginates_per 5
 
  accepts_nested_attributes_for :contents, :reject_if => lambda { |a| a[:song_id].empty? and a[:diapo_id].empty? }, :allow_destroy => true

  validates :fecha, presence: true

  def load_template(church)
    template = church.settings.first.presentation_template.split(',')
    
    template.each do |cont|
      self.contents.build(eval("{"+cont+"}"))

    end

  end

  def songs_list()
    list = ""
    self.contents.each do |content|
      if content.song
        list += content.song.title + ", "
      end
    end
    
    return list.chomp(',')
  end
  
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource :only => :live
  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = current_church.presentations.order('fecha desc').page params[:page]

  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    @presentation = current_church.presentations.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @presentation }
    end
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def live
    @presentation = Presentation.find(params[:id])
    @church = @presentation.church
    @anniversaries = @church.anniversaries.current_month

    respond_to do |format|
      format.html { render :layout => false } # show.html.erb
      format.json { render json: @presentation }
    end
  end

  # GET /presentations/new
  # GET /presentations/new.json
  def new
    @presentation = current_church.presentations.build
    @presentation.load_template(current_church)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @presentation }
    end
  end

  # GET /presentations/1/edit
  def edit
    @presentation = current_church.presentations.find(params[:id])
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = current_church.presentations.build(params[:presentation])

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render json: @presentation, status: :created, location: @presentation }
      else
        format.html { render action: "new" }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /presentations/1
  # PUT /presentations/1.json
  def update
    @presentation = current_church.presentations.find(params[:id])

    respond_to do |format|
      if @presentation.update_attributes(params[:presentation])
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation = current_church.presentations.find(params[:id])
    @presentation.destroy

    respond_to do |format|
      format.html { redirect_to presentations_url }
      format.json { head :no_content }
    end
  end

  def presentationbook_add
    
    sbpresentation = PresentationbookPresentation.new
    sbpresentation.presentation_id = params[:presentation_id]
    sbpresentation.presentationbook_id = params[:presentationbook_id]

    if sbpresentation.save
      respond_to do |format|
        format.js { render :js => "$('#presentation" + params[:presentation_id] + " .add_presentation').hide(); $('#presentation" + params[:presentation_id] + " .remove_presentation').show();" }
      end
    end
  end
  def presentationbook_remove

    sbpresentation = PresentationbookPresentation.where("presentationbook_id = ? and presentation_id = ?", params[:presentationbook_id], params[:presentation_id]).first



    if sbpresentation.destroy
      respond_to do |format|

        format.js { render :js => "$('#presentation" + params[:presentation_id] + " .add_presentation').show(); $('#presentation" + params[:presentation_id] + " .remove_presentation').hide();" }
      end
    end
  end



  def vote_add
    
    vote = current_user.votes.build
    vote.presentation_id = params[:presentation_id]
    if vote.save
      @votes = vote.presentation.votes.count
      respond_to do |format|
        format.js { render :js => "$('.presentation#{vote.presentation_id} .add_vote').next().show(); $('.presentation#{vote.presentation_id} .add_vote').hide();$('.presentation#{vote.presentation_id} .votes').html('(#{@votes})')" }
      end
    end
  end


end

app/views/presentations/_form.html.haml
.col-xs-12
  =nested_form_for @presentation do |f|
    .form-group
      %label.control-label Fecha
      =f.text_field :fecha, :class => 'form-control'


    %ul#sortable.list-group.col-xs-11
      =f.fields_for :contents, :wrapper => 'a', :class => 'form-inline' do |content|
        %li.list-group-item{:class => content.object.diapo_id ? '' : 'song-row'}
          .row
            .col-xs-1
              <span class="glyphicon glyphicon-sort"></span>
            =content.hidden_field :position, :class => 'form-control order'
            .col-xs-10.col-sm-8.song{:style => content.object.song_id ? '' : 'display: none'}
              =content.collection_select(:song_id, Song.order('title asc'), :id, :title, {:include_blank => ''}, :class => 'form-control')


            .col-xs-10.col-sm-8.diapo{:style => content.object.diapo_id ? '' : 'display: none'}
              =content.collection_select(:diapo_id, current_church.diapos, :id, :title, {:include_blank => ''}, :class => 'form-control')
            .col-sm-3.col-xs-12
              =content.link_to_remove "Remover"

    =f.link_to_add "Agregar Diapositiva", :contents, "data-target" => "#sortable", :class => 'btn btn-lg btn-default', :onclick => 'update_position(); content_type="diapo";'
    =f.link_to_add "Agregar Canción", :contents, "data-target" => "#sortable", :class => 'btn btn-lg btn-default', :onclick => 'update_position(); content_type="song";'



    =f.submit 'Actualizar Presentación', :class => 'btn btn-lg btn-primary'

app/views/presentations/edit.html.haml
.col-sm-12 
  %h1 Editar Presentación
=render 'form'

app/views/presentations/index.html.haml
.row
  .col-sm-8
    %h1 Presentaciones
  .col-sm-4.text-right
    =link_to('Nueva Presentación', new_presentation_url, :class => 'btn btn-primary btn-lg')

%hr

=paginate @presentations, :theme => 'twitter-bootstrap-3'

%table.table.table-bordered.table-hover.table-striped
  -@presentations.each do |pres|
    %tr
      %td=link_to(pres.fecha.strftime('%d/%m/%Y'), pres)
      %td.text-right=link_to(raw('<span class="glyphicon glyphicon-trash"></span>'), pres, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default ')

app/views/presentations/live.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=1024, user-scalable=no", name: "viewport"}/
    %title Your deck.js Presentation
    / Required stylesheet
    %link{href: "/core/deck.core.css", media: "screen", rel: "stylesheet"}/
    / Extension CSS files go here. Remove or add as needed.
    %link{href: "/extensions/goto/deck.goto.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/menu/deck.menu.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/navigation/deck.navigation.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/status/deck.status.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/scale/deck.scale.css", media: "screen", rel: "stylesheet"}/
    / Style theme. More available in /themes/style/ or create your own.
    %link{href: "/themes/style/swiss.css", media: "screen", rel: "stylesheet"}/
    / Transition theme. More available in /themes/transition/ or create your own.
    %link{href: "/themes/transition/fade.css", media: "screen", rel: "stylesheet"}/
    / Basic black and white print styles
    %link{href: "/core/print.css", media: "print", rel: "stylesheet"}/
    <link href='https://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>

    <meta property="og:title"              content="Presentación #{@presentation.fecha.strftime('%d/%m/%Y')}" />
    <meta property="og:description"        content="#{@presentation.songs_list}" />
    <meta property="og:image"              content="#{image_url('pf.jpg')}" />

    =stylesheet_link_tag 'live'

    / Required Modernizr file
    <link rel="stylesheet" href="http://yui.yahooapis.com/3.17.1/build/cssreset-context/cssreset-context.css" type="text/css">

    :css
      .song-slide {
        background: url(#{@church.settings.first.songs_background});
        background-size: cover;
      }  
      .song-slide h1 {
        color: #{@church.settings.first.songs_font_color};
        text-transform: #{@church.settings.first.songs_case};
      } 
      .song-slide h1 span{
        background-color: #{@church.settings.first.songs_text_bg_color};
        padding-left: 5px;
      }
      #anniversaries {
        background: url(#{@church.settings.first.anniversaries_background});
        background-size: cover;        
      }

    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    %script{src: "/modernizr.custom.js"}
    = javascript_include_tag "jquery.fittext"
    = javascript_include_tag "live"

  %body
    .deck-container
      / Begin slides. Just make elements with a class of slide.

      -@presentation.contents.order('position asc').each do |content|
        -if content.song
          %section.slide.song-slide
            %h1.title=content.song.title
          -diapo = content.song.sorted_array_lyric
          -diapo.each do |verse|
            -unless verse[:text].blank? # or verse.values[0].blank?
              %section.slide.song-slide
                %h1.verso=format_verse_diapo(verse[:text])
            
        -else
          -if content.diapo.background_url.blank?

            -if content.diapo.title == 'anniversaries'
              %section.slide#anniversaries
                %h2 Felicidades
                .well
                  -@anniversaries.each do |ann|
                    .row
                      .dato=ann.date.strftime('%d/%m')
                      .dato=ann.name
                      .dato.icon=image_tag('icons/' + ann.category + '/' + (rand(3)+1).to_s + '.png')
            -else
              %section.slide
                -if content.diapo.show_title
                  %h2=content.diapo.title
                %div=raw content.diapo.info

          -else
            %section.slide{:style => "background: url(#{content.diapo.background}) no-repeat center center fixed; -webkit-background-size: cover;   -moz-background-size: cover;   -o-background-size: cover;   background-size: cover;"}
              -if content.diapo.show_title
                %h2=content.diapo.title
              %div=raw content.diapo.info


    / End slides.
    / Begin extension snippets. Add or remove as needed.
    / deck.navigation snippet
    %div{"aria-role" => "navigation"}
      %a.deck-prev-link{href: "#", title: "Previous"} ←
      %a.deck-next-link{href: "#", title: "Next"} →
    / deck.status snippet
    %p.deck-status{"aria-role" => "status"}
      %span.deck-status-current
      \/
      %span.deck-status-total
    / deck.goto snippet
    %form.goto-form{action: ".", method: "get"}
      %label{for: "goto-slide"} Go to slide:
      %input#goto-slide{list: "goto-datalist", name: "slidenum", type: "text"}/
      %datalist#goto-datalist
      %input{type: "submit", value: "Go"}/
    / End extension snippets.
  / Required JS files.

  %script{src: "/core/deck.core.js"}
  / Extension JS files. Add or remove as needed.
  %script{src: "/extensions/menu/deck.menu.js"}
  %script{src: "/extensions/goto/deck.goto.js"}
  %script{src: "/extensions/status/deck.status.js"}
  %script{src: "/extensions/navigation/deck.navigation.js"}
  %script{src: "/extensions/scale/deck.scale.js"}
  %script{src: "/assets/jquery-fullscreen-min.js"}

  / Initialize the deck. You can put this in an external file if desired.
  :javascript
    $(function() {
      $.deck('.slide');
    });

app/views/presentations/new.html.haml
%h1 Nueva Presentación
=render 'form'

app/views/presentations/show.html.haml
.col-sm-12
  .row
    =link_to('On Air', live_presentation_url(@presentation), :class => 'col-sm-2 btn btn-danger btn-lg')
    =link_to('Editar', edit_presentation_url(@presentation), :class => 'col-sm-2 btn btn-default btn-lg')
.clearfix

-@presentation.contents.order('position asc').each do |content|
  .well
    -if content.song



      
      %h1=content.song.title
      -diapo = content.song.sorted_array_lyric(true)
      -if !content.song.order.blank?
        -diapo.each do |verse|
          %h5=verse[:label]
          %pre=chordify2(verse[:text])
            
      -else
        Le falta el orden de los versos..
        =link_to("Editar", edit_song_url(content.song))
    -else
      %h1=content.diapo.title
      %pre=raw content.diapo.info