config/routes.rb
Corobook::Application.routes.draw do

  resources :anniversaries


  resources :settings


  mount Ckeditor::Engine => '/ckeditor'

  resources :group_collaborators
  resources :groups
  resources :diapos
  resources :presentations do 
    member do 
      get :live
    end
  end

  resources :user_groups


  resources :songbooks do 
    member do 
      get :send_email
    end
  end


  resources :songs do
    member do 
      get :live
    end

    collection do
      get :vote_add
      get :songbook_add
      get :songbook_remove
    end
  end


  # authenticated :user do
  #   root :to => 'songs#index'
  # end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  attr_accessible :group_id, :role, :user_id
  belongs_to :group
  belongs_to :user

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_groups }
    end
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/new
  # GET /user_groups/new.json
  def new
    @user_group = UserGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/1/edit
  def edit
    @user_group = UserGroup.find(params[:id])
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_group = UserGroup.new(params[:user_group])

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
        format.json { render json: @user_group, status: :created, location: @user_group }
      else
        format.html { render action: "new" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_groups/1
  # PUT /user_groups/1.json
  def update
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      if @user_group.update_attributes(params[:user_group])
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group = UserGroup.find(params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url }
      format.json { head :no_content }
    end
  end
end

app/views/user_groups/_form.html.haml
= simple_form_for(@user_group) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :group_id
    = f.input :role

  .form-actions
    = f.button :submit

app/views/user_groups/edit.html.haml
%h1 Editing user_group

= render 'form'

= link_to 'Show', @user_group
\|
= link_to 'Back', user_groups_path

app/views/user_groups/index.html.haml
%h1 Listing user_groups

%table
  %tr
    %th User
    %th Group
    %th Role
    %th
    %th
    %th

  - @user_groups.each do |user_group|
    %tr
      %td= user_group.user_id
      %td= user_group.group_id
      %td= user_group.role
      %td= link_to 'Show', user_group
      %td= link_to 'Edit', edit_user_group_path(user_group)
      %td= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User group', new_user_group_path

app/views/user_groups/new.html.haml
%h1 New user_group

= render 'form'

= link_to 'Back', user_groups_path

app/views/user_groups/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_group.user_id
%p
  %b Group:
  = @user_group.group_id
%p
  %b Role:
  = @user_group.role

= link_to 'Edit', edit_user_group_path(@user_group)
\|
= link_to 'Back', user_groups_path