config/routes.rb
Corobook::Application.routes.draw do

  resources :anniversaries


  resources :settings


  mount Ckeditor::Engine => '/ckeditor'

  resources :group_collaborators
  resources :groups
  resources :diapos
  resources :presentations do 
    member do 
      get :live
    end
  end

  resources :user_groups


  resources :songbooks do 
    member do 
      get :send_email
    end
  end


  resources :songs do
    member do 
      get :live
    end

    collection do
      get :vote_add
      get :songbook_add
      get :songbook_remove
    end
  end


  # authenticated :user do
  #   root :to => 'songs#index'
  # end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/songbook.rb
class Songbook < ActiveRecord::Base
  attr_accessible :title, :fecha
  has_many :songbook_songs
  has_many :songs, :through => :songbook_songs
end

app/controllers/songbooks_controller.rb
class SongbooksController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /songbooks
  # GET /songbooks.json
  def index
    @songbooks = Songbook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songbooks }
    end
  end

  # GET /songbooks/1
  # GET /songbooks/1.json
  def show
    @songbook = Songbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @songbook }
    end
  end

  
  def send_email
    @songbook = Songbook.find(params[:id])

    current_user.group.users.each do |user|
      UserMailer.send_songbook(@songbook, user).deliver
    end

    
    respond_to do |format|
      format.html # new.html.erb
      format.js { render :js => "alert('enviado');" }
    end
  end

  # GET /songbooks/new
  # GET /songbooks/new.json
  def new
    @songbook = Songbook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @songbook }
    end
  end

  # GET /songbooks/1/edit
  def edit
    @songbook = Songbook.find(params[:id])
  end

  # POST /songbooks
  # POST /songbooks.json
  def create
    @songbook = Songbook.new(params[:songbook])

    respond_to do |format|
      if @songbook.save
        format.html { redirect_to @songbook, notice: 'Songbook was successfully created.' }
        format.json { render json: @songbook, status: :created, location: @songbook }
      else
        format.html { render action: "new" }
        format.json { render json: @songbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songbooks/1
  # PUT /songbooks/1.json
  def update
    @songbook = Songbook.find(params[:id])

    respond_to do |format|
      if @songbook.update_attributes(params[:songbook])
        format.html { redirect_to @songbook, notice: 'Songbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @songbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songbooks/1
  # DELETE /songbooks/1.json
  def destroy
    @songbook = Songbook.find(params[:id])
    @songbook.destroy

    respond_to do |format|
      format.html { redirect_to songbooks_url }
      format.json { head :no_content }
    end
  end
end

app/views/songbooks/_form.html.haml
= simple_form_for(@songbook) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

  .form-inputs
    = f.input :fecha

  .form-actions
    = f.button :submit

app/views/songbooks/edit.html.haml
%h1 Editing songbook

= render 'form'

= link_to 'Show', @songbook
\|
= link_to 'Back', songbooks_path

app/views/songbooks/index.html.haml
%h1 Songbooks

%table.table.table-bordered.table-hover.table-striped
  %tr
    %th Nombre
    %th
    %th

  - @songbooks.each do |songbook|
    %tr
      %td=link_to(songbook.title, songbook)
      %td
        -if current_user.role >= 5
          =link_to 'Send', send_email_songbook_path(songbook), :remote => true
          =link_to 'Edit', edit_songbook_path(songbook)
          =link_to 'Destroy', songbook, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Songbook', new_songbook_path

app/views/songbooks/new.html.haml
%h1 New songbook

= render 'form'

= link_to 'Back', songbooks_path

app/views/songbooks/show.html.haml
%p#notice= notice

%h2= @songbook.title

%ul
  -@songbook.songbook_songs.each do |sbs|
    %li=link_to(sbs.song.title, sbs.song)


-@songbook.songbook_songs.each do |sbs|
  %h4=sbs.song.title
  %p
    %strong Orden: 
    =sbs.song.order
  %pre{:style => "white-space: pre;"}=raw sbs.song.clean_lyric.gsub("\r", "<br />").upcase


= link_to 'Edit', edit_songbook_path(@songbook)
\|
= link_to 'Back', songbooks_path