config/routes.rb
Corobook::Application.routes.draw do

  resources :anniversaries


  resources :settings


  mount Ckeditor::Engine => '/ckeditor'

  resources :group_collaborators
  resources :groups
  resources :diapos
  resources :presentations do 
    member do 
      get :live
    end
  end

  resources :user_groups


  resources :songbooks do 
    member do 
      get :send_email
    end
  end


  resources :songs do
    member do 
      get :live
    end

    collection do
      get :vote_add
      get :songbook_add
      get :songbook_remove
    end
  end


  # authenticated :user do
  #   root :to => 'songs#index'
  # end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/song.rb
# -*- coding: utf-8 -*-
class Song < ActiveRecord::Base
  attr_accessible :author, :link, :lyric, :mood, :order, :reference, :title
  belongs_to :user
  belongs_to :group
  has_many :songbook_songs
  has_many :songbooks, :through => :songbook_songs
  has_many :votes

  validates :title, presence: true
  validates :lyric, presence: true
  validates :order, presence: true
  validates :group, presence: true
  validate :validate_sintax
  validate :validate_user_on_create
  
  before_validation :log_validation_state

  def validate_sintax
    if self.lyric.scan(/\[.*\]/i).blank?
      errors.add(:order, "No se encontraron versos en el texto. Ej: [CORO] ")
    end
  end

  def log_validation_state
    Rails.logger.info "=== SONG VALIDATION STATE ==="
    Rails.logger.info "Song ID: #{self.id}"
    Rails.logger.info "New record?: #{new_record?}"
    Rails.logger.info "User ID: #{user_id}"
    Rails.logger.info "Group ID: #{group_id}"
    Rails.logger.info "User present?: #{user.present?}"
    Rails.logger.info "Group present?: #{group.present?}"
    Rails.logger.info "================================"
  end

  def validate_user_on_create
    Rails.logger.info "Custom user validation - new_record?: #{new_record?}, user blank?: #{user.blank?}"
    if new_record? && user.blank?
      Rails.logger.error "Song validation failed - User required for new songs"
      errors.add(:user, "can't be blank")
    else
      Rails.logger.info "User validation passed - existing song or user present"
    end
  end


  def expiration_date_cannot_be_in_the_past
    if expiration_date.present? && expiration_date < Date.today
      errors.add(:expiration_date, "can't be in the past")
    end
  end



  def in_songbook?(sbid)
    !self.songbook_songs.where('songbook_id = ?', sbid).empty?
  end
  def clean_lyric
    lines = self.lyric.split(/\n/)
    clean_lyric = ""
    prev_chords = false
    lines.each do |line|
      chord_matches = line.scan(/\b[CDEFGAB](?:#|b)?(?:m|maj|dim|aug|sus[24]?)?(?:7|9|11|13)?\b/)
      line_without_spaces = line.gsub(/\s/, '')
      chord_content = chord_matches.join('')
      is_chord_line = (chord_matches.length >= 2) || 
                     (chord_content.length > 0 && line_without_spaces.length > 0 && 
                      (chord_content.length.to_f / line_without_spaces.length) >= 0.6)
      
      if is_chord_line and !prev_chords
        prev_chords = true
      else
        prev_chords = false
        clean_lyric += line
      end
    end
    return clean_lyric
  end
  # \b[CDEFGAB](?:#{1,2}|b{1,2})?(?:7?|m7?|sus2?)\b

  def hashed_lyric(show_chords = false)
    hash = { }
    actual_verse = ""

    self.lyric.each_line do |line|
      if line =~ /\[.*]/
        actual_verse = line.scan(/\[(.*)\]/i)[0][0]
        hash[actual_verse] = []
      else
        unless line.gsub(/\r\n/, '').blank?
          clean_line = line.gsub(/\r\n/, '')
          # Check if line is mostly chords by counting chord matches vs total content
          chord_matches = line.scan(/\b[CDEFGAB](?:#|b)?(?:m|maj|dim|aug|sus[24]?)?(?:7|9|11|13)?\b/)
          # Remove all whitespace and see if chords make up most of the content
          line_without_spaces = line.gsub(/\s/, '')
          chord_content = chord_matches.join('')
          
          # A line is considered chords if:
          # 1. It has at least 2 chord matches, OR
          # 2. Chord content makes up at least 60% of non-space characters
          is_chord_line = (chord_matches.length >= 2) || 
                         (chord_content.length > 0 && line_without_spaces.length > 0 && 
                          (chord_content.length.to_f / line_without_spaces.length) >= 0.6)
          
          if is_chord_line
            hash[actual_verse] << { line: clean_line, type: :chords} if show_chords
          else
            hash[actual_verse] << { line: clean_line, type: :text}
          end
        end
      end
    end

    return hash
  end

  def sorted_array_lyric(show_chords = false)

    hl = self.hashed_lyric(show_chords)
    array = []
    order = order_list
    count = 0
    order.each_with_index do |verse, index|
      verse.strip!
      part = Marshal.load( Marshal.dump( hl[verse] ) )

      if order[index] == order[index-1] and index > 0
        count += 1
        slash = "/" * count

        #tmp_verse = Marshal.load( Marshal.dump( part ) )
        part.select{|key| key[:type] == :text}.first[:line].prepend(slash)
        part.select{|key| key[:type] == :text}.last[:line] += slash

        array.pop
        array << { label: verse, text: part}
        #hl[verse] = tmp_verse
      else
        count = 1
        array << { label: verse, text: part}
      end
    end

    return array
  end

  def order_list
    self.order.gsub(', ', ',').split(',')
  end


  def diapo_mode(chords=false)
    versos = self.lyric.scan(/\[.*\]/i)
    hash = { }
    hash_actual = ''
    is_chord = false
    if !versos.blank?

      self.lyric.each_line do |line|

        is_verse = nil

        versos.each do |value|

          if line =~ /\[#{value[1..-2]}\]/
            is_verse = value[1..-2]
          end

        end

        if is_verse
          if hash[hash_actual]
            hash[hash_actual].gsub!(/<br>$/, '')
          end

          hash_actual = is_verse.upcase
          hash[hash_actual] = ''

        else
          chord_matches = line.scan(/\b[CDEFGAB](?:#|b)?(?:m|maj|dim|aug|sus[24]?)?(?:7|9|11|13)?\b/)
          line_without_spaces = line.gsub(/\s/, '')
          chord_content = chord_matches.join('')
          is_chord_line_diapo = (chord_matches.length >= 2) || 
                               (chord_content.length > 0 && line_without_spaces.length > 0 && 
                                (chord_content.length.to_f / line_without_spaces.length) >= 0.6)
          
          if is_chord_line_diapo and !is_chord
            is_chord = true
            hash[hash_actual] += line if chords
          else
            if chords
              hash[hash_actual] += line
            else
              hash[hash_actual] += line.gsub(/\n/, '<br>')
            end
            is_chord = false
          end
        end

      end
    end
    return hash
  end

  def songbooks_ago
    if self.songbooks.empty?
      return '∞'
    else
      sb = self.songbooks.order('fecha asc').last
      return Songbook.where('fecha > ?', sb.fecha).count
    end
  end


  def cantada_count
    if self.songbooks.empty?
      return 0
    else
      sb = self.songbooks.where('fecha > ?', Date.today-2.months)
      return sb.count
    end

  end

  def voted?(user)
    if !Vote.where('user_id = ? and song_id = ?', user.id, self.id).empty?
      return true
    else
      return false
    end
  end

  # Helper method to check if a user can edit this song
  def editable_by?(user)
    return false unless user && user.persisted?
    return true if user.has_role?(:admin)
    
    # Check if user belongs to the same group as the song
    return false unless self.group.present?
    
    # User can edit if they belong to the same group as the song
    # (song user_id can be nil for legacy songs)
    user.group == self.group || user.groups.include?(self.group)
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :live]
  before_action :check_user_has_group, only: [:new, :create]
  load_and_authorize_resource except: [:index, :show, :live]
  
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order(:title)
    @songbook = Songbook.last

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
    # No authorization needed - public access

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  def live
    @song = Song.find(params[:id])
    # No authorization needed - public access

    respond_to do |format|
      format.html { render :layout => false } # show.html.erb
      format.json { render json: @song }
    end
  end


  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
    authorize! :update, @song
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])
    @song.user = current_user
    # If user has a primary group, use it; otherwise use their first group from user_groups
    @song.group = current_user.group || current_user.groups.first

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])
    authorize! :update, @song

    # Filter out user_id and group_id to prevent them from being changed
    song_params = params[:song].except(:user_id, :group_id)
    
    Rails.logger.info "Song update - ID: #{@song.id}, user_id: #{@song.user_id}, group_id: #{@song.group_id}"
    Rails.logger.info "Original params: #{params[:song].keys.join(', ')}"
    Rails.logger.info "Filtered params: #{song_params.keys.join(', ')}"

    respond_to do |format|
      if @song.update_attributes(song_params)
        Rails.logger.info "Song update successful - ID: #{@song.id}, title: #{@song.title}"
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        Rails.logger.error "Song update failed - ID: #{@song.id}"
        Rails.logger.error "Validation errors: #{@song.errors.full_messages.join(', ')}"
        Rails.logger.error "Song state - user_id: #{@song.user_id}, group_id: #{@song.group_id}, new_record?: #{@song.new_record?}"
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    authorize! :destroy, @song
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  def songbook_add
    
    sbsong = SongbookSong.new
    sbsong.song_id = params[:song_id]
    sbsong.songbook_id = params[:songbook_id]

    if sbsong.save
      respond_to do |format|
        format.js { render :js => "$('#song" + params[:song_id] + " .add_song').hide(); $('#song" + params[:song_id] + " .remove_song').show();" }
      end
    end
  end
  def songbook_remove

    sbsong = SongbookSong.where("songbook_id = ? and song_id = ?", params[:songbook_id], params[:song_id]).first



    if sbsong.destroy
      respond_to do |format|

        format.js { render :js => "$('#song" + params[:song_id] + " .add_song').show(); $('#song" + params[:song_id] + " .remove_song').hide();" }
      end
    end
  end



  def vote_add
    
    vote = current_user.votes.build
    vote.song_id = params[:song_id]
    if vote.save
      @votes = vote.song.votes.count
      respond_to do |format|
        format.js { render :js => "$('.song#{vote.song_id} .add_vote').next().show(); $('.song#{vote.song_id} .add_vote').hide();$('.song#{vote.song_id} .votes').html('(#{@votes})')" }
      end
    end
  end

  private

  def check_user_has_group
    unless current_user.group || current_user.groups.any?
      redirect_to root_path, alert: 'Debes pertenecer a un grupo para crear canciones. Contacta al administrador.'
    end
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.haml
.col-sm-12
  = simple_form_for(@song) do |f|
    .form-inputs
      .form-group
        =f.input :title, input_html: { class: 'form-control'}
      .row
        .col-sm-12
          .row
            .col-sm-6

              .form-group
                =f.input :author, input_html: { class: 'form-control'}

            .col-sm-6
              .form-group
                =f.input :reference, input_html: { class: 'form-control'}, label: 'Referencia Bíblica'

      .form-group
        =f.input :mood, collection: [['Alegre', 30], ['Intermedia', 20],['Tranquila']], prompt: "Select your age", input_html: { class: 'form-control'}, label: 'Rítmo'

      .form-group
        =f.input :lyric, :input_html => { :style => "font-family: lucida console; height: 800px", class: 'form-control'}
      .form-group
        =f.input :order, input_html: { class: 'form-control'}

      .form-group
        =f.input :link, input_html: { class: 'form-control'}

    .form-actions
      = f.button :submit, input_html: { class: 'btn btn-default'}

app/views/songs/edit.html.haml
%h1 Editar Canción

- if @song.errors.any?
  .alert.alert-error
    %h4= "#{pluralize(@song.errors.count, "error")} prohibited this song from being saved:"
    %ul
      - @song.errors.full_messages.each do |message|
        %li= message

.row
  .col-sm-12
    =render 'form'

%hr 
=link_to 'Ver', @song
\|
=link_to 'Regresar', songs_path, :class => 'btn btn-default'

app/views/songs/index.html.haml
.row
  .col-sm-8
    %h1 Canciones
  .col-sm-4.text-right
    =link_to('Nueva Canción', new_song_path, :class => 'btn btn-primary btn-lg')
%hr 

%table.table.table-bordered.table-hover.table-striped
  %tr
    %th Titulo
    %th Autor
    %th Referencia
    %th Intensidad
    %th Grupo
    %th Creado por
    %th

  - @songs.each do |song|
    %tr{:id => "song"+song.id.to_s}
      %td=link_to song.title, song
      %td=song.author
      %td=song.reference
      %td=song.mood
      %td=song.group.name if song.group
      %td=song.user.name if song.user

      %td
        -if song.valid?
          =link_to(raw('<span class="glyphicon glyphicon-fullscreen"></span>'), live_song_url(song), :class => 'btn btn-default ')
    
        -if current_user and can?(:update, song) and song.editable_by?(current_user)
          =link_to(raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_song_url(song), :class => 'btn btn-default ')
        -if current_user and can?(:destroy, song) and song.editable_by?(current_user)
          =link_to(raw('<span class="glyphicon glyphicon-trash"></span>'), song, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default ')


%br

app/views/songs/live.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=1024, user-scalable=no", name: "viewport"}/
    %title Your deck.js Presentation
    / Required stylesheet
    %link{href: "/core/deck.core.css", media: "screen", rel: "stylesheet"}/
    / Extension CSS files go here. Remove or add as needed.
    %link{href: "/extensions/goto/deck.goto.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/menu/deck.menu.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/navigation/deck.navigation.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/status/deck.status.css", media: "screen", rel: "stylesheet"}/
    %link{href: "/extensions/scale/deck.scale.css", media: "screen", rel: "stylesheet"}/
    / Style theme. More available in /themes/style/ or create your own.
    %link{href: "/themes/style/swiss.css", media: "screen", rel: "stylesheet"}/
    / Transition theme. More available in /themes/transition/ or create your own.
    %link{href: "/themes/transition/fade.css", media: "screen", rel: "stylesheet"}/
    / Basic black and white print styles
    %link{href: "/core/print.css", media: "print", rel: "stylesheet"}/
    / Required Modernizr file
    <link rel="stylesheet" href="http://yui.yahooapis.com/3.17.1/build/cssreset-context/cssreset-context.css" type="text/css">

    =stylesheet_link_tag "application"

    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    %script{src: "/modernizr.custom.js"}


    = javascript_include_tag "jquery.fittext"
    = javascript_include_tag "live"

  %body
    .deck-container
      / Begin slides. Just make elements with a class of slide.


      %section.slide.song-slide
        %h1.title=@song.title
      -diapo = @song.sorted_array_lyric
      -diapo.each do |verse|
        -unless verse[:text].blank? # or verse.values[0].blank?
          %section.slide.song-slide
            %h1.verso=format_verse_diapo(verse[:text])


    / End slides.
    / Begin extension snippets. Add or remove as needed.
    / deck.navigation snippet
    %div{"aria-role" => "navigation"}
      %a.deck-prev-link{href: "#", title: "Previous"} ←
      %a.deck-next-link{href: "#", title: "Next"} →
    / deck.status snippet
    %p.deck-status{"aria-role" => "status"}
      %span.deck-status-current
      \/
      %span.deck-status-total
    / deck.goto snippet
    %form.goto-form{action: ".", method: "get"}
      %label{for: "goto-slide"} Go to slide:
      %input#goto-slide{list: "goto-datalist", name: "slidenum", type: "text"}/
      %datalist#goto-datalist
      %input{type: "submit", value: "Go"}/
    / End extension snippets.
  / Required JS files.

  %script{src: "/core/deck.core.js"}
  / Extension JS files. Add or remove as needed.
  %script{src: "/extensions/menu/deck.menu.js"}
  %script{src: "/extensions/goto/deck.goto.js"}
  %script{src: "/extensions/status/deck.status.js"}
  %script{src: "/extensions/navigation/deck.navigation.js"}
  %script{src: "/extensions/scale/deck.scale.js"}
  / Initialize the deck. You can put this in an external file if desired.
  :javascript
    $(function() {
      $.deck('.slide');
    });

app/views/songs/new.html.haml
%h1 Nueva Canción
.row
  .col-sm-12
    =render 'form'

%hr
=link_to 'Regresar', songs_path, :class => 'btn btn-default'

app/views/songs/show.html.haml
%p#notice= notice

.row
  .col-sm-11
    %h1
      =@song.title
      .small=@song.reference
  .col-sm-1.text-right
    -if current_user and can?(:update, @song) and @song.editable_by?(current_user)
      =link_to(raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_song_url(@song), :class => 'btn btn-default ')

-if !@song.author.blank?
  %p
    %b By:
    =@song.author

-if @song.group
  %p
    %b Grupo:
    =@song.group.name

-if @song.user
  %p
    %b Creado por:
    =@song.user.name

%p
  %b Order:
  = @song.order

.well
  -diapo = @song.sorted_array_lyric(true)
  -if !@song.order.blank?
    -diapo.each do |verse|
      %h5=verse[:label]
      %pre=chordify2(verse[:text]) 

-unless @song.link.blank?
  %p
    %b Video:
    %br

  %iframe{:width => "560", :height => "315", :src => "//www.youtube.com/embed/" + @song.link.scan(/=(.*)$/)[0][0], :frameborder => "0", :allowfullscreen => true}